# Default values for fake-review-app.
# This is a YAML-formatted file.

replicaCount: 1

image:
  repository: shalinibaghel/fake-review-flask  # ✅ DockerHub Image (replace if needed)
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}
securityContext: {}

service:
  type: LoadBalancer      # ✅ Expose app to Internet
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

autoscaling:
  enabled: false

nodeSelector: {}

tolerations: []

affinity: {}
